-- ============================================================
-- SUMANVI / J S K ENTERPRISES - SUPABASE SETUP
-- Run this entire script in Supabase SQL Editor.
-- ============================================================

-- 1. Admin allow-list
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

drop policy if exists "Admins can read their own admin record" on public.admin_users;
create policy "Admins can read their own admin record"
on public.admin_users
for select
to authenticated
using (auth.uid() = user_id);

-- IMPORTANT:
-- After creating your admin in Authentication > Users, run:
-- insert into public.admin_users (user_id)
-- values ('PASTE-ADMIN-USER-UUID-HERE');

-- 2. Products
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric(12,2) not null default 0,
  offer date not null,
  image_url text,
  image_path text,
  description text not null,
  specs jsonb not null default '{}'::jsonb,
  featured boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

drop policy if exists "Public can view products" on public.products;
create policy "Public can view products"
on public.products
for select
to anon, authenticated
using (true);

drop policy if exists "Admins can insert products" on public.products;
create policy "Admins can insert products"
on public.products
for insert
to authenticated
with check (
  exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  )
);

drop policy if exists "Admins can update products" on public.products;
create policy "Admins can update products"
on public.products
for update
to authenticated
using (
  exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  )
);

drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products"
on public.products
for delete
to authenticated
using (
  exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  )
);

-- 3. Blogs
create table if not exists public.blogs (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  category text not null default 'Industry Guides',
  icon text default 'book-open',
  publish_date date not null default current_date,
  excerpt text not null,
  content text not null,
  image_url text,
  image_path text,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.blogs enable row level security;

drop policy if exists "Public can view published blogs" on public.blogs;
create policy "Public can view published blogs"
on public.blogs
for select
to anon, authenticated
using (published = true or exists (
  select 1 from public.admin_users
  where user_id = auth.uid()
));

drop policy if exists "Admins can insert blogs" on public.blogs;
create policy "Admins can insert blogs"
on public.blogs
for insert
to authenticated
with check (
  exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  )
);

drop policy if exists "Admins can update blogs" on public.blogs;
create policy "Admins can update blogs"
on public.blogs
for update
to authenticated
using (
  exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  )
);

drop policy if exists "Admins can delete blogs" on public.blogs;
create policy "Admins can delete blogs"
on public.blogs
for delete
to authenticated
using (
  exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  )
);

-- 4. Storage buckets
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

insert into storage.buckets (id, name, public)
values ('blog-images', 'blog-images', true)
on conflict (id) do update set public = true;

-- 5. Storage RLS
drop policy if exists "Public can view product images" on storage.objects;
create policy "Public can view product images"
on storage.objects
for select
to public
using (bucket_id = 'product-images');

drop policy if exists "Admins can upload product images" on storage.objects;
create policy "Admins can upload product images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'product-images'
  and exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  )
);

drop policy if exists "Admins can update product images" on storage.objects;
create policy "Admins can update product images"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'product-images'
  and exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  )
)
with check (
  bucket_id = 'product-images'
  and exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  )
);

drop policy if exists "Admins can delete product images" on storage.objects;
create policy "Admins can delete product images"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'product-images'
  and exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  )
);

drop policy if exists "Public can view blog images" on storage.objects;
create policy "Public can view blog images"
on storage.objects
for select
to public
using (bucket_id = 'blog-images');

drop policy if exists "Admins can upload blog images" on storage.objects;
create policy "Admins can upload blog images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'blog-images'
  and exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  )
);

drop policy if exists "Admins can update blog images" on storage.objects;
create policy "Admins can update blog images"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'blog-images'
  and exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  )
)
with check (
  bucket_id = 'blog-images'
  and exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  )
);

drop policy if exists "Admins can delete blog images" on storage.objects;
create policy "Admins can delete blog images"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'blog-images'
  and exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  )
);

-- 6. Grants for the browser client.
grant select on public.products to anon, authenticated;
grant select on public.blogs to anon, authenticated;
grant select on public.admin_users to authenticated;

grant insert, update, delete on public.products to authenticated;
grant insert, update, delete on public.blogs to authenticated;

grant usage, select on sequence public.products_id_seq to authenticated;

-- ============================================================
-- OPTIONAL SAMPLE BLOGS
-- ============================================================
insert into public.blogs
  (title, slug, category, icon, publish_date, excerpt, content, published)
values
(
  'Energy-Efficient Electrical Bulbs vs. Traditional Bulbs',
  'energy-efficient-electrical-bulbs-vs-traditional-bulbs',
  'Energy Efficiency',
  'lightbulb',
  current_date,
  'LED bulbs use much less electricity than traditional incandescent bulbs while providing excellent brightness.',
  'Electrical LED bulbs are a smarter and more energy-efficient alternative to traditional incandescent bulbs. They consume significantly less electricity while providing the same or better brightness. They also generate less heat and generally last much longer than traditional incandescent bulbs. For offices, warehouses, factories and other B2B applications, switching to efficient LED lighting can reduce electricity consumption and maintenance requirements.',
  true
),
(
  'Benefits of Electrical LED Bulbs',
  'benefits-of-electrical-led-bulbs',
  'Energy Efficiency',
  'zap',
  current_date,
  'Learn the key benefits of using modern LED bulbs for homes, offices, shops and industrial spaces.',
  'LED bulbs offer low energy consumption, long service life, instant brightness, low heat generation and a wide range of colour temperatures. For businesses, these benefits can translate into lower operating costs and fewer replacement cycles.',
  true
)
on conflict (slug) do nothing;
